// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhkLmx6yhAYnoIaW-oq1V0XJMUgvaQ57E',
    appId: '1:17892490109:web:0c8a598e1e585cc1b4aa14',
    messagingSenderId: '17892490109',
    projectId: 'chatdemo-b5b38',
    authDomain: 'chatdemo-b5b38.firebaseapp.com',
    storageBucket: 'chatdemo-b5b38.appspot.com',
    measurementId: 'G-Z49JD1F76N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPoUCPtj1D6_fap7YbZPk6OXzNQDsZ8Bc',
    appId: '1:17892490109:android:e1dfe0a1f1aee2fab4aa14',
    messagingSenderId: '17892490109',
    projectId: 'chatdemo-b5b38',
    storageBucket: 'chatdemo-b5b38.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAX_Z5bJz9Q8ns5SFjGZ_OwuYYj_BIje_M',
    appId: '1:17892490109:ios:c5d93b286bd508dab4aa14',
    messagingSenderId: '17892490109',
    projectId: 'chatdemo-b5b38',
    storageBucket: 'chatdemo-b5b38.appspot.com',
    iosClientId: '17892490109-8793ojbejaquha8bein0jo9ra2lgssj6.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAX_Z5bJz9Q8ns5SFjGZ_OwuYYj_BIje_M',
    appId: '1:17892490109:ios:2453d780579c5066b4aa14',
    messagingSenderId: '17892490109',
    projectId: 'chatdemo-b5b38',
    storageBucket: 'chatdemo-b5b38.appspot.com',
    iosClientId: '17892490109-pjimotu9bonivtb3ud0lqhado15j7gmt.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseChat.RunnerTests',
  );
}
